name: Your Workflow Name

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-get-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install requests library
        run: pip install requests

      - name: Run Python script
        run: python main.py

      - name: Commit and push results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Pull the latest changes to avoid push rejection
          # git pull origin main --rebase

          # Add new files, commit, and push
          git add responses/
          git commit -m "Add new response file"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Meh-ar/github_action.git

